sky:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tCCK6DfMXZFPZxZB6qN
    access-key-secret: ZgBBhd015DUNAcMgCmM5ILHlkMvyR9
    bucket-name: tanhuacouldplatform
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx356d477c0c55505f
    secret: 0303df0c5037fae1f79e6d552ec72720
