sky:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tCCK6DfMXZFPZxZB6qN
    access-key-secret: ZgBBhd015DUNAcMgCmM5ILHlkMvyR9
    bucket-name: tanhuacouldplatform
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx356d477c0c55505f
    secret: 0303df0c5037fae1f79e6d552ec72720
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: E:\code\itheima\sky-take-out-porject\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: E:\code\itheima\sky-take-out-porject\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
